services:
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

  chatbot:
    depends_on:
      - redis
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.redis.host" : "redis",
          "spring.redis.port" : "6379"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
